defaults:
  - _self_
  - task: pusht_image

name: train_ibc_dfo_hybrid
_target_: cot_policy.workspace.train_ibc_image_workspace.TrainIBCUnetImageWorkspace

task_name: ${task.name}
dataset_type: ${task.dataset_type}
shape_meta: ${task.shape_meta}
exp_name: "default"
models_dir: /media/storage/soho/exps/paper/models/
outputs_dir: /media/storage/soho/exps/outputs/

horizon: 2
n_obs_steps: 2
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
policy_type: "ibc_policy"

obs_encoder:
    _target_: cot_policy.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: cot_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: [76, 76]
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True

policy:
  _target_: cot_policy.policy.ibc_hybrid_image_policy.IbcDfoHybridImagePolicy

  shape_meta: ${shape_meta}

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  dropout: 0.1
  train_n_neg: 1024
  pred_n_iter: 5
  pred_n_samples: 1024
  kevin_inference: False
  andy_train: False
  obs_encoder_group_norm: True
  eval_fixed_crop: True
  crop_shape: [76, 76]

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  resume_dir: null
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 1500
  num_epochs: 1502
  gradient_accumulate_every: 1
  # training loop control
  # in epochs
  rollout_every: 50
  checkpoint_every: 50
  val_every: 10
  sample_every: 10
  sample_max_batch: 128
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  use_ema: False

logging:
  project: cot_policy
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False

multi_run:
  run_dir: ${outputs_dir}${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_${dataset_type}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}_${dataset_type}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${models_dir}${policy_type}_False_${task_name}_${dataset_type}
  sweep:
    dir: ${models_dir}${policy_type}_False_${task_name}_${dataset_type}
    subdir: ${hydra.job.num}
