shape_meta:
  action:
    shape:
    - 2
  obs:
    agent_pos:
      shape:
      - 6
      type: low_dim


dataset_dir: /media/storage/soho/
dataset_type: null
abs_action: true
dataset:
  _target_: cot_policy.dataset.d4rl_maze2d_dataset.Maze2dDataset
  horizon: ${horizon}
  max_train_episodes: 90
  pad_after: 7
  pad_before: 1
  seed: 42
  val_ratio: 0.02
  zarr_path: ${task.dataset_dir}data/maze2d/dataset_maze2d-custom-2-v0.zarr
env_runner:
  _target_: cot_policy.env_runner.d4rl_maze2d_runner.Maz2dRunner
  fps: 10
  env_name: maze2d-custom-2-v0
  legacy_test: true
  max_steps: 300
  n_action_steps: 8
  n_envs: null
  n_obs_steps: 2
  n_test: 50
  n_test_vis: 10
  n_train: 6
  n_train_vis: 2
  past_action: false
  test_start_seed: 4300000
  train_start_seed: 0

name: maze2d-2
task_name: maze2d-2